# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - test

cache:
  key: shared-cache
  paths:
    - .julia
    - .cache/pip
    - .cache/pypoetry

test:
  image: python:3.12-slim
  stage: test
  variables:
    JULIA_VERSION: "1.11.5"
    POETRY_VERSION: "2.1.3"
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia"
    PYTHONUNBUFFERED: 1
    IPOPT_VERSION: "3.14.0"
  before_script:
    - ls
    - pwd
    - apt-get update && apt-get install -y curl
    # GLPK
    - apt-get install -y libglpk-dev glpk-utils
    - glpsol --version
    # IPOPT
    - apt-get install -y gfortran  gcc  g++  make  wget  unzip  pkg-config  liblapack-dev  libblas-dev  libtool  coinor-libipopt-dev  build-essential  git  cmake  python3-dev  python3-pip  libopenblas-dev  libmumps-seq-dev  libmetis-dev
    - mkdir /opt/ipopt && cd /opt/ipopt
    - git clone https://github.com/coin-or/Ipopt.git
    - cd Ipopt
    - mkdir ThirdParty && cd ThirdParty
    - git clone https://github.com/coin-or-tools/ThirdParty-Mumps.git
    - cd ThirdParty-Mumps && ./get.Mumps
    - ./configure
    - make && make install
    - cd /opt/ipopt/Ipopt/ThirdParty
    - git clone https://github.com/coin-or-tools/ThirdParty-ASL.git
    - cd ThirdParty-ASL && ./get.ASL
    - ./configure
    - make && make install
    - cd /opt/ipopt/Ipopt
    - mkdir build && cd build
    # Not using HSL for testing environment, because it requires license and stuff
    - ../configure --with-mumps-cflags=-I/usr/include/mumps_seq --with-mumps-lflags=-ldmumps_seq --without-hsl
    - make
    - make test 
    - make install

    # Highs
    - cd /opt
    - mkdir highs && cd highs
    - git clone https://github.com/ERGO-Code/HiGHS.git
    - cmake -S . -B build
    - cmake --build build
    - cd build && ctest
    # Julia
    - cd /tmp
    - wget https://julialang-s3.julialang.org/bin/linux/x64/${JULIA_VERSION:0:4}/julia-$JULIA_VERSION-linux-x86_64.tar.gz
    - tar -xzf julia-$JULIA_VERSION-linux-x86_64.tar.gz
    - mv julia-$JULIA_VERSION /opt/julia
    - ln -s /opt/julia/bin/julia /usr/bin/julia
    - julia --version
    - cd /builds/recon4imd/cobra_arrow
    - julia --project=./src/service/optimization_service/julia -e "import Pkg; Pkg.instantiate()"

    # Poetry
    - cd /builds/recon4imd/cobra_arrow
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$HOME/.local/bin:$PATH"
    - poetry config virtualenvs.create true
    - poetry install --no-interaction --no-ansi --no-root
    - source `poetry env info --path`/bin/activate
  script:
    # - sh startAll > /dev/null 2>&1 &
    - poetry run pytest --junitxml=junit.xml --timeout=10
  artifacts:
    when: always
    paths:
      - ./
    reports:
      junit: junit.xml
